                                                Data Structures, Functions, Numpy & Pandas

Section A: Data Structures & Control Structures 

In [1]:
my_list = [5, 2, 9, 1, 7]
print("Original list:", my_list)

Original list: [5, 2, 9, 1, 7]


In [2]:
# append
my_list.append(10)
print("After append:", my_list)

After append: [5, 2, 9, 1, 7, 10]


In [3]:
# extend
my_list.extend([11, 12])
print("After extend:", my_list)

After extend: [5, 2, 9, 1, 7, 10, 11, 12]


In [4]:
# remove
my_list.remove(9)
print("After remove:", my_list)

After remove: [5, 2, 1, 7, 10, 11, 12]


In [5]:
# insert
my_list.insert(2, 100)
print("After insert:", my_list)

After insert: [5, 2, 100, 1, 7, 10, 11, 12]


In [6]:
my_list.pop()
print("After pop:", my_list)

After pop: [5, 2, 100, 1, 7, 10, 11]


In [7]:
# index
print("Index of 100:", my_list.index(100))

Index of 100: 2


In [8]:
# count
print("Count of 1:", my_list.count(1))

Count of 1: 1


In [9]:
# sort
my_list.sort()
print("After sort:", my_list)


After sort: [1, 2, 5, 7, 10, 11, 100]


In [10]:
# reverse
my_list.reverse()
print("After reverse:", my_list)


After reverse: [100, 11, 10, 7, 5, 2, 1]


In [11]:
# clear
my_list.clear()
print("After clear:", my_list)

After clear: []


Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why. 

In [14]:
students = ("Ram", "Bob","siva")
print("Original tuple:", students)

Original tuple: ('Ram', 'Bob', 'siva')


In [13]:
# try to change second name
students[1] = "David"

TypeError: 'tuple' object does not support item assignment

In [15]:
#It gives an error message beacuse tuples are immutable,their values cannot be changes once created

3) Create a set of integers with some duplicate values. Print the set and explain the output.

In [17]:
my_set = {111, 278, 323, 278, 40, 111, 235,278}

print("The Set is:", my_set)

The Set is: {323, 278, 40, 235, 111}


In [18]:
#repeated values are printed only once in the result.it happens beacuse sets doesn't allow duplicate values.

4) Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [19]:
my_dict={
    "name":"sri",
    "age":22,
    "city":"Chennai"
}
print("Original dictionary:",my_dict)
my_dict["age"]=23
my_dict["email"]="sri03@gmail.com"

print("Updated dictionary:",my_dict)

Original dictionary: {'name': 'sri', 'age': 22, 'city': 'Chennai'}
Updated dictionary: {'name': 'sri', 'age': 23, 'city': 'Chennai', 'email': 'sri03@gmail.com'}


5) Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [21]:
age=17
if age>=18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Not eligible to vote


6) Given a 'marks' variable, print the grade: - 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'

In [22]:
marks=82
if marks>=90:
    print("A")
elif marks>=75:
    print("B")
elif marks>=50:
    print("C")
else:
    print("Fail")

B


7) Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [23]:
num=248
if num>0:
    print("Positive number")
    if num %2==0:
        print("It is also even")
    else:
        print("It is odd")
elif num==0:
    print("Zero")
else:
    print("Negative number")

Positive number
It is also even


                                                        Section B: Numpy 

8) Create: 
- A scalar using np.array(5) 
- A 1D array with values 1 to 5 
- A 2D array (2x3) with values from 10 to 60 in steps of 10 

In [24]:
import numpy as np
import pandas as pd

# scalar
scalar=np.array(5)
print("Scalar:", scalar)

# 1D array
arr1=np.array([21,78,34,4,95])
print("1D array:", arr1)

# 2D array (2x3)
arr2 = np.array([[10,20,30], [40,50,60]])
print("2D array:\n", arr2)

Scalar: 5
1D array: [21 78 34  4 95]
2D array:
 [[10 20 30]
 [40 50 60]]


9) Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [25]:
rand_arr=np.random.randint(0,100,(4,4))
print("Random 4x4 array:\n", rand_arr)

Random 4x4 array:
 [[97 11 67 60]
 [92 17  1 66]
 [ 8  4 92 70]
 [13 75 94 71]]


10) Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'. 

In [26]:
arr3 = np.array([[1,12,34], [42, 25, 76], [7, 81, 19]])

df = pd.DataFrame(arr3, columns=['A','B','C'])
print("DataFrame:\n", df)

DataFrame:
     A   B   C
0   1  12  34
1  42  25  76
2   7  81  19
